# permissions for end users to edit blueprints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercode-editor-role
rules:
  - apiGroups:
      - clustercode.github.io
    resources:
      - blueprints
      - tasks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - clustercode.github.io
    resources:
      - blueprints/status
      - tasks/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
