
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clustercode.github.io
  resources:
  - encodingplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustercode.github.io
  resources:
  - encodingplans/status
  verbs:
  - get
  - patch
  - update
