---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: clustercode
        image: $E2E_IMAGE
        args:
        - -v
        - operate
        - --operator.clustercode-image
        - $E2E_IMAGE
        - --scan.role-name=TEST_FILE_ID-clustercode-editor-role
