resources:
- ../../config/manager
- ../../config/rbac
- pv.yaml
patchesStrategicMerge:
- deployment.yaml
namespace: TEST_NAMESPACE
namePrefix: TEST_FILE_ID-

commonLabels:
  app.kubernetes.io/name: e2e
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: TEST_FILE_ID
