---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: $RANDOM
    spec:
      containers:
      - name: clustercode
        image: localhost:5000/clustercode/operator:e2e
        imagePullPolicy: Always
        args:
        - operate
        - -v
