apiVersion: clustercode.github.io/v1alpha1
kind: ClustercodePlan
metadata:
  name: test-plan
spec:
  scanSchedule: "*/1 * * * *"
  sourceVolume:
    name: fuckyou
    emptyDir: {}
  sourceVolumeSubdir: input
